[default]
locale = "en-us"

[default.extend-identifiers]
# Pydantic uses British spelling for this method name
customise = "customise"

[files]
ignore-vcs = true
extend-exclude = [
  ".git",
  "LICENSE",
  "*policyreports*.yaml",
  "clusterpolicyreports.yaml"
]

