[default]
locale = "en-us"

[default.extend-identifiers]
# No custom identifiers needed - US spelling is default

[files]
ignore-vcs = true
extend-exclude = [
  ".git",
  "LICENSE",
  "*policyreports*.yaml",
  "clusterpolicyreports.yaml"
]

